controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_handleft_controller:
      type: position_controllers/GripperActionController

    panda_handright_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_impedance_example_controller:
      type: franka_example_controllers/JointImpedanceExampleController


cartesian_impedance_controller:
  ros__parameters:
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    command_interfaces:
      - effort

joint_impedance_example_controller:
  ros__parameters:
    arm_id: panda
    k_gains:
      - 56.0
      - 56.0
      - 48.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5
      
panda_arm_controller:
  ros__parameters:
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      panda_joint1: { trajectory: 0.2, goal: 0.1 }
      panda_joint2: { trajectory: 0.2, goal: 0.1 }
      panda_joint3: { trajectory: 0.2, goal: 0.1 }
      panda_joint4: { trajectory: 0.2, goal: 0.1 }
      panda_joint5: { trajectory: 0.2, goal: 0.1 }
      panda_joint6: { trajectory: 0.2, goal: 0.1 }
      panda_joint7: { trajectory: 0.2, goal: 0.1 }
      #panda_finger_joint1: { trajectory: 0.2, goal: 0.1 }
      #panda_finger_joint2: { trajectory: 0.2, goal: 0.1 }

panda_handleft_controller:
  ros__parameters:
    joint: panda_finger_joint1

panda_handright_controller:
  ros__parameters:
    joint: panda_finger_joint2
      